const players = [
  " Kevin Durant",
  "Tim Duncan",
  "Stephen Curry",
  "Steve Nash",
  "Michael Jordan",
  "Charles Barkley",
  "Shaquille O'Neal",
  "Chris Paul",
  "Carmelo Anthony",
  "LeBron James",
  "Shawn Kemp",
  "Gary Payton",
  "Kobe Bryant",
  "Magic Johnson",
  "Larry Bird",
  "Kevin Garnett",
  "Dirk Nowitzki",
  "Omri Casspi",
  "Deni Avdija",
]
